### PR TITLE
refactor repo_util* for go-1.7

### PR DESCRIPTION
**Pull request by lemmi**
#18 #19
This is the alternative approach to the problem with the early EOF from reads since go 1.7. 
Changes made:

repo_utils_reader.go:
- readerDecompressed takes io.ReadCloser so the underlying file can be closed and is not leaked
- newReadCloser wraps two io.ReadClosers
- convenient function wrapReadCloser added to retain the old behaviour

repo_utils.go

- type and length is now parsed with a simple call to fmt.Fscanf, makes getLengthZeroTerminated obsolete
    - this could potentially be changed to something more low level
- file is read sequentially without seeking

the EOF bug can potentially still happen in https://github.com/lemmi/git/blob/e11be8e1fd55c2ec996a27eb3665d33024c771ad/repo_utils.go#L143 .
This could need another rewrite, too, but I'm not yet familiar with the git pack format. A lot of other places in that file could really benefit from encoding/binary. I'll open up issues for these parts.

If there are coding style issues, let me know and please test these changes, too. They work here, also the small go test passes.

### CODE REVIEW

**Comment by Unknwon** [comment]
Does the code still works under go1.6

**Comment by lemmi** [comment]
I ran all my tests on 1.6 again without errors.
And as far as I can tell, these changes use nothing 1.7 specific like new methods on some of the Readers.

**Comment by snicol** [comment]
Using [this test script](https://gist.github.com/snicol/2d012456e6cf926f88657eb59a488ec4 ) on 1.7 I get this: 

      go run get_commit.go                                                                                                                                                                   
      2016/08/18 12:22:37 EOF
      exit status 1

However it does work on 1.6.

**Comment by lemmi** [comment]
@snicol I did not commit to master. Did you checkout the go1.7 branch?

**Comment by snicol** [comment]
Ah that was it, oops! I just tested on 1.6 and 1.7 on Darwin and linux-amd64 and can't see any regressions. Good work! 👍

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
